### Get All Products
GET http://localhost:3000/products

###Get product details by brand
GET http://localhost:3000/products/HP

###Create Product
POST http://localhost:3000/products
Content-Type: application/json

{
    "productId":1,
    "name":"TV",
    "brand":"LG",
    "price":130000
}

###Update product
PUT http://localhost:3000/products
Content-Type: application/json

{
    "productId":1,
    "name":"Laptop",
    "brand":"HP",
    "price":50000
}

###Delete Product by ID
DELETE http://localhost:3000/products/1